# Exported from Render on 2025-10-30T11:59:47Z
version: "1"
services:
- type: web
  name: Mobilerotaryai
  runtime: static
  repo: https://github.com/lukeponga-dev/mobilerotaryai
  envVars:
  - key: GEMINI_API_KEY
    sync: true
  buildCommand: yarn install; yarn build
  staticPublishPath: ./dist
  autoDeployTrigger: commit
