// data/technicalTerms.ts

/**
 * A dictionary of technical terms related to the Mazda RX-8 and rotary engines.
 * The keys are the terms to be matched in the text (case-insensitive).
 * The values are the definitions that will appear in the tooltip.
 */
export const technicalTerms: Record<string, string> = {
  'apex seals': 'Spring-loaded seals at the tips of the rotor that separate the three combustion chambers. Critical for maintaining compression.',
  'rotor housing': 'The main housing in which the rotor spins. The inner surface is where combustion occurs.',
  'renesis': 'The name of the Mazda RX-8\'s naturally aspirated 13B rotary engine, short for "Rotary Engine GENESIS".',
  'eccentric shaft': 'The equivalent of a crankshaft in a piston engine. The rotors spin around lobes on this shaft, which then transfers power to the drivetrain.',
  'e-shaft': 'A common abbreviation for the Eccentric Shaft.',
  'side housings': 'The flat plates that sandwich the rotor housing on either side, containing the intake and exhaust ports.',
  'engine flooding': 'A common rotary issue where excess fuel washes oil off the internal seals, causing a temporary loss of compression and preventing the engine from starting.',
  'de-flooding': 'The procedure to clear a flooded rotary engine, typically involving cutting fuel supply and cranking the engine to expel excess gasoline.',
  'premixing': 'The practice of adding a small amount of 2-stroke oil to the fuel tank to improve lubrication of the apex seals, especially in high-performance applications.',
  'sohn adapter': 'An aftermarket device that allows the oil metering pump (OMP) to draw clean 2-stroke oil from a separate reservoir instead of using engine oil for lubrication.',
  'omp': 'Oil Metering Pump. A device that injects small amounts of oil into the combustion chamber to lubricate the seals.',
  'catalytic converter': 'An emissions control device that converts toxic gases from the exhaust into less harmful substances. Prone to clogging in RX-8s if the ignition system is faulty.',
  'hei spark tester': 'A High Energy Ignition (HEI) tester used to check the strength of the spark from an ignition coil. A strong, blue spark is healthy; a weak, yellow/orange spark indicates a problem.',
  'obd-ii': 'On-Board Diagnostics II. A standardized system on modern vehicles that monitors engine and emissions performance and reports diagnostic trouble codes (DTCs).',
  'dtc': 'Diagnostic Trouble Code. A code generated by the OBD-II system that corresponds to a specific vehicle fault.',
  'compression test': 'A diagnostic procedure to measure the pressure generated by each face of the rotor. A rotary-specific tester is required for accurate results.',
};
